const util = require('util')
const BitX = require('bitx')

AsyncBitX = BitX
AsyncBitX.prototype.getTicker = util.promisify(BitX.prototype.getTicker)
AsyncBitX.prototype.getAllTickers = util.promisify(BitX.prototype.getAllTickers)
AsyncBitX.prototype.getOrderBook = util.promisify(BitX.prototype.getOrderBook)
AsyncBitX.prototype.getTrades = util.promisify(BitX.prototype.getTrades)
AsyncBitX.prototype.getOrderList = util.promisify(BitX.prototype.getOrderList)
AsyncBitX.prototype.getLimits = util.promisify(BitX.prototype.getLimits)
AsyncBitX.prototype.stopOrder = util.promisify(BitX.prototype.stopOrder)
AsyncBitX.prototype.postBuyOrder = util.promisify(BitX.prototype.postBuyOrder)
AsyncBitX.prototype.postMarketBuyOrder = util.promisify(BitX.prototype.postMarketBuyOrder)
AsyncBitX.prototype.postSellOrder = util.promisify(BitX.prototype.postSellOrder)
AsyncBitX.prototype.postMarketSellOrder = util.promisify(BitX.prototype.postMarketSellOrder)
AsyncBitX.prototype.getOrder = util.promisify(BitX.prototype.getOrder)
AsyncBitX.prototype.getBalance = util.promisify(BitX.prototype.getBalance)
AsyncBitX.prototype.getFundingAddress = util.promisify(BitX.prototype.getFundingAddress)
AsyncBitX.prototype.createFundingAddress = util.promisify(BitX.prototype.createFundingAddress)
AsyncBitX.prototype.getTransactions = util.promisify(BitX.prototype.getTransactions)
AsyncBitX.prototype.getWithdrawals = util.promisify(BitX.prototype.getWithdrawals)
AsyncBitX.prototype.getWithdrawal = util.promisify(BitX.prototype.getWithdrawal)
AsyncBitX.prototype.requestWithdrawal = util.promisify(BitX.prototype.requestWithdrawal)
AsyncBitX.prototype.cancelWithdrawal = util.promisify(BitX.prototype.cancelWithdrawal)

module.exports = AsyncBitX